const STORAGE_KEY='edge-journal-v1';
const seedTrades=[
 {id:1,date:'2026-08-12',symbol:'BTC/USDT',direction:'long',result:'win',rr:2.4,amount:1000000,pnl:184000,reason:'일봉 지지 구간 반등과 거래량 증가 확인',chart:null},
 {id:2,date:'2026-08-14',symbol:'NVDA',direction:'long',result:'loss',rr:1.5,amount:800000,pnl:-72000,reason:'돌파 매매, 거래량 확인이 부족했음',chart:null},
 {id:3,date:'2026-08-16',symbol:'ETH/USDT',direction:'short',result:'win',rr:2.1,amount:1200000,pnl:156000,reason:'4시간봉 추세선 리테스트 후 양봉 전환',chart:null},
 {id:4,date:'2026-08-18',symbol:'TSLA',direction:'long',result:'win',rr:1.8,amount:700000,pnl:91000,reason:'전고점 돌파 후 지지 확인, 계획가 진입',chart:null}
];
let state=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||{trades:seedTrades,reviews:{},notes:[]};
let activeNoteId=null;
let chartPeriod='day';
let editingTradeId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>`${n>=0?'+':'-'}₩${Math.abs(n).toLocaleString('ko-KR')}`;
const dateLabel=d=>new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric'}).format(new Date(d+'T00:00:00'));
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};

function showView(name){
  $$('.view').forEach(v=>v.classList.remove('active')); $$('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));
  $(`#${name}View`).classList.add('active');
  const titles={dashboard:['TRADING OVERVIEW','오늘도 원칙대로.'],trades:['TRADE LOG','모든 매매 기록'],reviews:['REVIEW CYCLE','10회 단위 복기'],notes:['QUICK NOTES','트레이딩 메모장']};
  $('#pageEyebrow').textContent=titles[name][0]; $('#pageTitle').textContent=titles[name][1];
  if(name==='dashboard')requestAnimationFrame(drawChart); if(name==='trades')renderTradeGrid(); if(name==='reviews')renderReviews(); if(name==='notes')renderNotes();
}

function renderDashboard(){
  const t=[...state.trades].sort((a,b)=>a.date.localeCompare(b.date)); const pnl=t.reduce((s,x)=>s+x.pnl,0); const wins=t.filter(x=>x.result==='win').length; const invested=t.reduce((s,x)=>s+x.amount,0); const rate=invested?pnl/invested*100:0; const progress=t.length%10;
  $('#totalPnl').textContent=money(pnl); $('#totalPnl').className=pnl>=0?'positive':'negative'; $('#pnlSub').textContent=`총 ${t.length}번의 매매`;
  $('#winRate').textContent=t.length?`${Math.round(wins/t.length*100)}%`:'0%'; $('#winSub').textContent=`${wins}승 ${t.length-wins}패`;
  $('#avgRr').textContent=t.length?`${(t.reduce((s,x)=>s+x.rr,0)/t.length).toFixed(1)}R`:'0.0R'; $('#reviewProgress').textContent=`${progress} / 10`; $('#progressBar').style.width=`${progress*10}%`; $('#returnBadge').textContent=`${rate>=0?'+':''}${rate.toFixed(1)}%`;
  $('#recentTrades').innerHTML=t.slice(-5).reverse().map(rowHtml).join('')||'<tr><td colspan="6" class="empty-row">아직 기록된 매매가 없습니다.</td></tr>';
  $('#reviewPreview').innerHTML=`<div class="review-progress-card"><strong>${progress}<small> / 10</small></strong><p>다음 복기까지 <b>${10-progress}</b>번의 매매가 남았습니다.</p><div class="mini-progress"><span style="width:${progress*10}%"></span></div><button class="primary-btn full" data-go="reviews">복기 현황 보기</button></div><div class="review-tip"><b>이번 사이클 체크</b><p>${t.length?'손익보다 진입 근거를 잘 지켰는지 확인하세요.':'첫 매매의 진입 근거부터 기록해보세요.'}</p></div>`;
  $('#emptyChart').style.display=t.length?'none':'grid'; requestAnimationFrame(drawChart);
}
function rowHtml(t){return `<tr><td>${dateLabel(t.date)}</td><td><b>${escapeHtml(t.symbol)}</b></td><td><span class="result-pill ${t.result}">${t.result==='win'?'승':'패'}</span></td><td>${t.rr}R</td><td class="${t.pnl>=0?'positive':'negative'}">${money(t.pnl)}</td><td>${escapeHtml(t.reason).slice(0,36)}</td></tr>`}

function drawChart(){
 const canvas=$('#performanceChart'); if(!canvas||!canvas.offsetWidth)return; const dpr=devicePixelRatio||1,w=canvas.offsetWidth,h=canvas.offsetHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);
 const trades=[...state.trades].sort((a,b)=>a.date.localeCompare(b.date)); if(!trades.length)return;
 const buckets=new Map();trades.forEach(t=>{const d=new Date(t.date+'T00:00:00');let key=t.date;if(chartPeriod==='week'){const monday=new Date(d);monday.setDate(d.getDate()-((d.getDay()+6)%7));key=monday.toISOString().slice(0,10)}else if(chartPeriod==='month')key=t.date.slice(0,7);else if(chartPeriod==='year')key=t.date.slice(0,4);buckets.set(key,(buckets.get(key)||0)+t.pnl/t.amount*100)});
 let cum=0;const pts=[...buckets.values()].map(value=>{cum+=value;return cum});const min=Math.min(0,...pts),max=Math.max(0,...pts),range=max-min||1,pad={x:42,y:22};
 c.font='10px DM Sans';c.fillStyle='#8a8a8a';c.strokeStyle='#e5e5e5';c.lineWidth=1;for(let i=0;i<5;i++){let y=pad.y+(h-pad.y*2)*i/4;c.beginPath();c.moveTo(pad.x,y);c.lineTo(w-10,y);c.stroke();let val=max-(range*i/4);c.fillText(`${val.toFixed(1)}%`,2,y+3)}
 const xy=pts.map((p,i)=>({x:pad.x+(w-pad.x-15)*(pts.length===1?.5:i/(pts.length-1)),y:pad.y+(max-p)/range*(h-pad.y*2)}));const grad=c.createLinearGradient(0,pad.y,0,h);grad.addColorStop(0,'rgba(25,25,25,.20)');grad.addColorStop(1,'rgba(25,25,25,0)');c.beginPath();c.moveTo(xy[0].x,h-pad.y);xy.forEach(p=>c.lineTo(p.x,p.y));c.lineTo(xy.at(-1).x,h-pad.y);c.fillStyle=grad;c.fill();c.beginPath();xy.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.strokeStyle='#222';c.lineWidth=2.5;c.stroke();xy.forEach(p=>{c.beginPath();c.arc(p.x,p.y,3,0,7);c.fillStyle='#fff';c.fill();c.strokeStyle='#222';c.lineWidth=2;c.stroke()});
}

function renderTradeGrid(){const q=$('#tradeSearch').value.toLowerCase(),f=$('#tradeFilter').value;const list=[...state.trades].reverse().filter(t=>(f==='all'||t.result===f)&&(t.symbol.toLowerCase().includes(q)||t.reason.toLowerCase().includes(q)));$('#tradeGrid').innerHTML=list.map(t=>`<article class="panel trade-card ${t.result}" data-view-trade="${t.id}" tabindex="0"><div class="trade-chart">${t.chart?`<img src="${t.chart}" alt="${escapeHtml(t.symbol)} 차트">`:'<div class="no-image">차트 이미지 없음</div>'}</div><div class="trade-card-body"><div class="trade-card-top"><div><span class="trade-date">${t.date}</span><h3>${escapeHtml(t.symbol)}</h3><span class="direction-pill ${t.direction||'unset'}">${t.direction==='long'?'LONG · 롱':t.direction==='short'?'SHORT · 숏':'방향 미지정'}</span></div><span class="result-pill ${t.result}">${t.result==='win'?'승리':'패배'}</span></div><div class="trade-metrics"><span>손익비<b>${t.rr}R</b></span><span>투입 금액<b>₩${t.amount.toLocaleString()}</b></span><span>손익<b class="${t.pnl>=0?'positive':'negative'}">${money(t.pnl)}</b></span></div><p class="trade-reason">${escapeHtml(t.reason)}</p><div class="card-actions"><button class="text-btn" data-edit-trade="${t.id}">수정</button><button class="danger-btn" data-delete-trade="${t.id}">삭제</button></div></div></article>`).join('')||'<div class="panel empty-row">조건에 맞는 매매가 없습니다.</div>'}

function renderReviews(){const completed=Math.floor(state.trades.length/10),progress=state.trades.length%10;$('#cycleRing').innerHTML=`<strong>${progress}</strong><span>/ 10</span>`;let html='';for(let n=completed;n>=1;n--){const r=state.reviews[n];html+=`<article class="review-cycle"><div class="cycle-label"><small>CYCLE</small><strong>#${String(n).padStart(2,'0')}</strong><small>${n*10-9}–${n*10}번째 매매</small></div>${r?`<div class="panel review-cell"><span>잘한 점</span><p>${escapeHtml(r.good)}</p></div><div class="panel review-cell"><span>고칠 점</span><p>${escapeHtml(r.improve)}</p></div><div class="panel review-cell"><span>다음 원칙</span><p>${escapeHtml(r.rule)}</p><button class="text-btn" data-review="${n}">수정</button></div>`:`<div class="panel review-cell pending-cycle" style="grid-column:span 3"><p>10회의 매매가 완료되었습니다. 지금 복기해보세요.</p><button class="primary-btn" data-review="${n}">복기 작성</button></div>`}</article>`}html+=`<article class="panel pending-cycle"><div><p class="eyebrow">CURRENT CYCLE #${String(completed+1).padStart(2,'0')}</p><h2>${progress}개의 매매 기록됨</h2><p>복기까지 ${10-progress}개가 남았습니다.</p></div><div class="mini-progress" style="width:220px"><span style="width:${progress*10}%"></span></div></article>`;$('#reviewList').innerHTML=html}

function renderNotes(){const q=$('#noteSearch').value.toLowerCase();const notes=[...state.notes].sort((a,b)=>b.updated-a.updated).filter(n=>(n.title+n.body).toLowerCase().includes(q));$('#noteList').innerHTML=notes.map(n=>`<div class="note-list-item ${n.id===activeNoteId?'active':''}" data-note="${n.id}"><strong>${escapeHtml(n.title||'제목 없음')}</strong><p>${escapeHtml(n.body||'내용 없음')}</p><small>${new Date(n.updated).toLocaleString('ko-KR')}</small></div>`).join('')||'<div class="empty-row">메모가 없습니다.</div>';renderEditor()}
function renderEditor(){const n=state.notes.find(n=>n.id===activeNoteId);if(!n){$('#noteEditor').innerHTML='<div class="note-placeholder"><span>▤</span><h2>매매 아이디어를 놓치지 마세요.</h2><p>왼쪽에서 메모를 선택하거나 새 메모를 만들어보세요.</p></div>';return}const images=n.images||[];$('#noteEditor').innerHTML=`<div class="editor-top"><input class="editor-title" id="noteTitle" value="${attr(n.title)}" placeholder="메모 제목"><div><span class="save-state">자동 저장</span> <button class="danger-btn" id="deleteNote">삭제</button></div></div><textarea class="editor-body" id="noteBody" placeholder="아이디어, 관찰, 원칙을 자유롭게 적어보세요.">${escapeHtml(n.body)}</textarea><div class="note-images">${images.map((src,index)=>`<figure><img src="${src}" alt="메모 첨부 이미지 ${index+1}"><button data-remove-note-image="${index}" aria-label="이미지 삭제">×</button></figure>`).join('')}</div><label class="note-image-upload"><input id="noteImageInput" type="file" accept="image/*" multiple hidden><span>＋ 사진 추가</span><small>PNG, JPG · 장당 최대 2MB</small></label>`}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function attr(v=''){return escapeHtml(v)}
function optimizeImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.82))};img.src=reader.result};reader.readAsDataURL(file)})}

function openTradeForm(id=null){
  editingTradeId=id;const form=$('#tradeForm');form.reset();$('#formError').textContent='';$('#fileName').textContent='파일을 선택하거나 드래그하세요';
  const trade=state.trades.find(t=>t.id===id);$('#tradeModalEyebrow').textContent=trade?'EDIT TRADE':'NEW TRADE';$('#tradeModalTitle').textContent=trade?'매매 기록 수정':'매매 기록하기';$('#tradeSubmitBtn').textContent=trade?'수정 저장':'기록 저장';
  if(trade){form.date.value=trade.date;form.symbol.value=trade.symbol;form.direction.value=trade.direction||'long';form.result.value=trade.result;form.rr.value=trade.rr;form.amount.value=trade.amount;form.pnl.value=trade.pnl;form.reason.value=trade.reason;$('#fileName').textContent=trade.chart?'기존 차트 이미지 유지':'파일을 선택하거나 드래그하세요'}else form.date.value=new Date().toISOString().slice(0,10);
  tradeModal.showModal();
}
function openTradeDetail(id){
  const t=state.trades.find(t=>t.id===id);if(!t)return;const modal=$('#tradeDetailModal');modal.dataset.tradeId=id;$('#detailTitle').textContent=t.symbol;$('#tradeDetailContent').innerHTML=`${t.chart?`<img class="detail-chart" src="${t.chart}" alt="${escapeHtml(t.symbol)} 차트">`:'<div class="detail-chart no-image">차트 이미지 없음</div>'}<div class="detail-badges"><span class="direction-pill ${t.direction||'unset'}">${t.direction==='long'?'LONG · 롱':t.direction==='short'?'SHORT · 숏':'방향 미지정'}</span><span class="result-pill ${t.result}">${t.result==='win'?'승리':'패배'}</span></div><div class="detail-grid"><div><span>날짜</span><b>${t.date}</b></div><div><span>손익비</span><b>${t.rr}R</b></div><div><span>투입 금액</span><b>₩${t.amount.toLocaleString()}</b></div><div><span>손익 금액</span><b class="${t.pnl>=0?'positive':'negative'}">${money(t.pnl)}</b></div></div><div class="detail-reason"><span>매매 근거</span><p>${escapeHtml(t.reason)}</p></div>`;modal.showModal();
}
function deleteTrade(id){if(!confirm('이 매매 기록을 삭제할까요?'))return false;state.trades=state.trades.filter(t=>t.id!==id);save();renderTradeGrid();renderDashboard();toast('매매 기록을 삭제했습니다.');return true}

$('#today').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date());
$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)showView(go.dataset.go);const del=e.target.closest('[data-delete-trade]');if(del){e.stopPropagation();deleteTrade(+del.dataset.deleteTrade);return}const edit=e.target.closest('[data-edit-trade]');if(edit){e.stopPropagation();openTradeForm(+edit.dataset.editTrade);return}const card=e.target.closest('[data-view-trade]');if(card)openTradeDetail(+card.dataset.viewTrade);const rev=e.target.closest('[data-review]');if(rev)openReview(+rev.dataset.review);const note=e.target.closest('[data-note]');if(note){activeNoteId=+note.dataset.note;renderNotes()}const removeImage=e.target.closest('[data-remove-note-image]');if(removeImage){const active=state.notes.find(n=>n.id===activeNoteId);if(active){active.images=active.images||[];active.images.splice(+removeImage.dataset.removeNoteImage,1);active.updated=Date.now();save();renderNotes();toast('사진을 삭제했습니다.')}}if(e.target.id==='deleteNote'&&confirm('이 메모를 삭제할까요?')){state.notes=state.notes.filter(n=>n.id!==activeNoteId);activeNoteId=null;save();renderNotes();toast('메모를 삭제했습니다.')}});
const tradeModal=$('#tradeModal');$('#openTradeModal').onclick=()=>openTradeForm();$$('[data-close]').forEach(b=>b.onclick=()=>tradeModal.close());$('#tradeForm [name=chart]').onchange=e=>$('#fileName').textContent=e.target.files[0]?.name||'파일을 선택하거나 드래그하세요';
$('#tradeForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),file=e.target.chart.files[0];if(file?.size>2*1024*1024){$('#formError').textContent='이미지는 2MB 이하로 올려주세요.';return}const old=state.trades.find(t=>t.id===editingTradeId);let chart=old?.chart||null;if(file)chart=await new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)});let pnl=Number(f.get('pnl'));const result=f.get('result');if(result==='loss')pnl=-Math.abs(pnl);if(result==='win')pnl=Math.abs(pnl);const trade={id:editingTradeId||Date.now(),date:f.get('date'),symbol:f.get('symbol').trim(),direction:f.get('direction'),result,rr:Number(f.get('rr')),amount:Number(f.get('amount')),pnl,reason:f.get('reason').trim(),chart};if(old)state.trades[state.trades.indexOf(old)]=trade;else state.trades.push(trade);save();e.target.reset();tradeModal.close();renderDashboard();if($('#tradesView').classList.contains('active'))renderTradeGrid();toast(old?'매매 기록을 수정했습니다.':state.trades.length%10===0?'10회 완료! 복기할 시간입니다.':'매매 기록을 저장했습니다.');editingTradeId=null};
$('#tradeSearch').oninput=renderTradeGrid;$('#tradeFilter').onchange=renderTradeGrid;window.onresize=()=>{if($('#dashboardView').classList.contains('active'))drawChart()};
$$('[data-period]').forEach(button=>button.onclick=()=>{chartPeriod=button.dataset.period;$$('[data-period]').forEach(item=>item.classList.toggle('active',item===button));drawChart()});
$$('[data-detail-close]').forEach(button=>button.onclick=()=>$('#tradeDetailModal').close());$('#detailEdit').onclick=()=>{const id=Number($('#tradeDetailModal').dataset.tradeId);$('#tradeDetailModal').close();openTradeForm(id)};$('#detailDelete').onclick=()=>{const id=Number($('#tradeDetailModal').dataset.tradeId);if(deleteTrade(id))$('#tradeDetailModal').close()};
$('#tradeGrid').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-view-trade]')){e.preventDefault();openTradeDetail(+e.target.dataset.viewTrade)}};
function openReview(cycle){const r=state.reviews[cycle]||{};$('#reviewModalTitle').textContent=`Cycle #${String(cycle).padStart(2,'0')} 복기`;const f=$('#reviewForm');f.cycle.value=cycle;f.good.value=r.good||'';f.improve.value=r.improve||'';f.rule.value=r.rule||'';$('#reviewModal').showModal()}$$('[data-review-close]').forEach(b=>b.onclick=()=>$('#reviewModal').close());$('#reviewForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.reviews[f.get('cycle')]={good:f.get('good'),improve:f.get('improve'),rule:f.get('rule')};save();$('#reviewModal').close();renderReviews();toast('복기를 저장했습니다.')};
$('#newNote').onclick=()=>{const n={id:Date.now(),title:'새 메모',body:'',images:[],updated:Date.now()};state.notes.push(n);activeNoteId=n.id;save();renderNotes();setTimeout(()=>$('#noteTitle')?.select(),0)};$('#noteSearch').oninput=renderNotes;document.addEventListener('input',e=>{if(!['noteTitle','noteBody'].includes(e.target.id))return;const n=state.notes.find(n=>n.id===activeNoteId);n.title=$('#noteTitle').value;n.body=$('#noteBody').value;n.updated=Date.now();save();const s=$('.save-state');s.textContent='저장됨';clearTimeout(window.noteTimer);window.noteTimer=setTimeout(()=>renderNotes(),700)});
document.addEventListener('change',async e=>{if(e.target.id!=='noteImageInput')return;const files=[...e.target.files];if(!files.length)return;if(files.some(file=>file.size>10*1024*1024)){toast('이미지는 장당 10MB 이하만 가능합니다.');return}const note=state.notes.find(n=>n.id===activeNoteId);if(!note)return;toast('사진을 최적화하는 중입니다.');try{const encoded=await Promise.all(files.map(optimizeImage));note.images=[...(note.images||[]),...encoded];note.updated=Date.now();try{save();renderNotes();toast(`${encoded.length}장의 사진을 추가했습니다.`)}catch(error){note.images.splice(-encoded.length);toast('브라우저 저장공간이 부족합니다. 기존 사진을 줄여주세요.')}}catch(error){toast('사진을 읽지 못했습니다. 다른 파일을 선택해주세요.')}});
renderDashboard();
