const STORAGE_KEY='edge-journal-v1';
let state=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||{trades:[],reviews:{},notes:[]};
let activeNoteId=null;
let chartPeriod='day';
let editingTradeId=null;
let activeTradeTeam='all';
let activeReportTeam='all';
let tradingReportController=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>`${n>=0?'+':'-'}₩${Math.abs(n).toLocaleString('ko-KR')}`;
const dateLabel=d=>new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric'}).format(new Date(d+'T00:00:00'));
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};

function showView(name){
  $$('.view').forEach(v=>v.classList.remove('active')); $$('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));
  $(`#${name}View`).classList.add('active');
  $('main').classList.toggle('immersive', ['chat','positions','reports','tradingReports','research','organization'].includes(name));
  const titles={dashboard:['FUND COMMAND CENTER','AI 펀드 운영 현황'],chat:['FUND TEAM NETWORK','네트워크'],organization:['ORGANIZATION MAP','AI 펀드팀 조직도'],trades:['B-GRADE EXECUTION','트레이딩 매매일지'],positions:['LIVE POSITION MONITOR','트레이딩팀 현 포지션'],reports:['A-GRADE INTELLIGENCE','시황 리포트'],tradingReports:['TRADING PERFORMANCE','Trading Reports'],research:['X-GRADE RESEARCH','연구 라이브러리'],notes:['PERSONAL NOTES','개인 메모']};
  $('#pageEyebrow').textContent=titles[name][0]; $('#pageTitle').textContent=titles[name][1];
  if(name==='dashboard')requestAnimationFrame(drawChart); if(name==='chat')renderChat(); if(name==='trades')renderTradeGrid(); if(name==='tradingReports')loadTradingReports(); if(name==='research')renderResearch(); if(name==='organization')renderOrganization(); if(name==='notes')renderNotes();
}

const reportNumber=(value,digits=0)=>Number.isFinite(Number(value))?Number(value).toLocaleString('ko-KR',{minimumFractionDigits:digits,maximumFractionDigits:digits}):'—';
const reportPercent=value=>Number.isFinite(Number(value))?`${Number(value)>=0?'+':''}${reportNumber(value,1)}%`:'—';
function reportState(kind,title,detail){const stateEl=$('#tradingReportState'),content=$('#tradingReportContent');stateEl.hidden=false;content.hidden=true;stateEl.className=`report-state panel ${kind}`;stateEl.innerHTML=`${kind==='loading'?'<span class="state-spinner" aria-hidden="true"></span>':'<span class="state-icon" aria-hidden="true">'+(kind==='error'?'!':'◇')+'</span>'}<div><b>${escapeHtml(title)}</b><p>${escapeHtml(detail)}</p>${kind==='error'?'<button type="button" class="secondary-btn report-retry">다시 시도</button>':''}</div>`}
function renderTradingReports(data){
  const k=data.kpis||{},teams=Array.isArray(data.teams)?data.teams:[],allocation=Array.isArray(data.assetAllocation)?data.assetAllocation:[],weekly=data.weekly||{},sentiment=data.sentiment||{};
  const hasData=Object.keys(k).length||teams.length||allocation.length||Object.keys(weekly).length||Object.keys(sentiment).length;
  if(!hasData){reportState('empty','표시할 Trading Reports가 없습니다.','선택한 팀의 성과 데이터가 API에 생성되면 이곳에 표시됩니다.');$('#tradingReportSync').textContent='데이터 없음';return}
  $('#tradingReportState').hidden=true;$('#tradingReportContent').hidden=false;$('#tradingReportSync').textContent=data.updatedAt?`업데이트 ${new Date(data.updatedAt).toLocaleString('ko-KR')}`:'업데이트 시간 미제공';
  const metrics=[['누적 손익',Number.isFinite(Number(k.cumulativePnl))?money(Number(k.cumulativePnl)):'—','pnl'],['평균 RR',Number.isFinite(Number(k.averageRr))?`${reportNumber(k.averageRr,2)}R`:'—','rr'],['포지션',reportNumber(k.positions),'positions'],['승률',Number.isFinite(Number(k.winRate))?`${reportNumber(k.winRate,1)}%`:'—','win'],['수익률',reportPercent(k.returnRate),'return']];
  $('#reportKpis').innerHTML=metrics.map(([label,value,key],i)=>`<article class="panel report-kpi ${i===0?'primary':''}"><span>${label}</span><strong class="${key==='pnl'&&Number(k.cumulativePnl)<0?'negative':''}">${value}</strong><small>${activeReportTeam==='all'?'전체 팀':'선택 팀'} 기준</small></article>`).join('');
  $('#reportWeek').textContent=weekly.period||'최근 7일';
  $('#weeklyPerformance').innerHTML=`<div class="weekly-result"><strong>${reportPercent(weekly.returnRate)}</strong><span>주간 수익률</span></div><div class="review-columns"><div><h4>✓ 잘한 점</h4><ul>${(weekly.wins||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')||'<li>기록 없음</li>'}</ul></div><div><h4>↗ 개선점</h4><ul>${(weekly.improvements||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')||'<li>기록 없음</li>'}</ul></div></div>`;
  const total=allocation.reduce((sum,x)=>sum+(Number(x.weight)||0),0);$('#allocationTotal').textContent=`합계 ${reportNumber(total,1)}%`;$('#assetAllocation').innerHTML=allocation.map(x=>`<div class="allocation-row"><div><b>${escapeHtml(x.asset||'미분류')}</b><span>${reportNumber(x.weight,1)}%</span></div><div class="allocation-track"><i style="width:${Math.max(0,Math.min(100,Number(x.weight)||0))}%"></i></div></div>`).join('')||'<p class="inline-empty">자산 배분 데이터가 없습니다.</p>';
  $('#teamReportList').innerHTML=teams.map(t=>`<article><header><div><span>${escapeHtml(t.teamName||teamNames[t.team]||t.team||'팀')}</span><h4>${escapeHtml(t.title||'주간 리포트')}</h4></div><strong>${reportPercent(t.returnRate)}</strong></header><p>${escapeHtml(t.summary||'요약이 없습니다.')}</p></article>`).join('')||'<p class="inline-empty">팀별 리포트가 없습니다.</p>';
  renderSentiment('#cryptoSentiment','CRYPTO FEAR & GREED','코인',sentiment.crypto);renderSentiment('#usSentiment','US FEAR & GREED','미국 증시',sentiment.usStocks);
}
function renderSentiment(selector,eyebrow,label,item){const value=Number(item?.value);$(selector).innerHTML=`<div><p class="eyebrow">${eyebrow}</p><h3>${label} 공포·탐욕 지수</h3></div>${Number.isFinite(value)?`<div class="sentiment-value"><strong>${Math.max(0,Math.min(100,value))}</strong><span>${escapeHtml(item.label||'중립')}</span></div><div class="sentiment-scale"><i style="left:${Math.max(0,Math.min(100,value))}%"></i></div>`:'<p class="inline-empty">지수 데이터가 없습니다.</p>'}`}
async function loadTradingReports(){
  tradingReportController?.abort();tradingReportController=new AbortController();reportState('loading','Trading Reports를 불러오는 중입니다.','성과 API 연결 상태를 확인하고 있습니다.');$('#tradingReportSync').textContent='동기화 중';
  try{const response=await fetch(`/api/trading-reports?team=${encodeURIComponent(activeReportTeam)}`,{headers:{Accept:'application/json'},signal:tradingReportController.signal});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();renderTradingReports(data&&typeof data==='object'?data:{})}catch(error){if(error.name==='AbortError')return;reportState('error','Trading Reports를 불러오지 못했습니다.','연결을 확인한 뒤 다시 시도해 주세요. 기존 값이나 샘플 데이터는 표시하지 않습니다.');$('#tradingReportSync').textContent='연결 오류'}
}

function renderDashboard(){
  const t=[...state.trades].sort((a,b)=>a.date.localeCompare(b.date)); const pnl=t.reduce((s,x)=>s+x.pnl,0); const wins=t.filter(x=>x.result==='win').length; const invested=t.reduce((s,x)=>s+x.amount,0); const rate=invested?pnl/invested*100:0;
  $('#totalPnl').textContent=money(pnl); $('#totalPnl').className=pnl>=0?'positive':'negative'; $('#pnlSub').textContent=`총 ${t.length}번의 매매`;
  $('#winRate').textContent=t.length?`${Math.round(wins/t.length*100)}%`:'0%'; $('#winSub').textContent=`${wins}승 ${t.length-wins}패`;
  $('#avgRr').textContent=t.length?`${(t.reduce((s,x)=>s+x.rr,0)/t.length).toFixed(1)}R`:'0.0R'; $('#returnBadge').textContent=`${rate>=0?'+':''}${rate.toFixed(1)}%`;
  $('#recentTrades').innerHTML=t.slice(-5).reverse().map(rowHtml).join('')||'<tr><td colspan="6" class="empty-row">아직 기록된 매매가 없습니다.</td></tr>';
  $('#emptyChart').style.display=t.length?'none':'grid'; requestAnimationFrame(drawChart);
}
function rowHtml(t){return `<tr><td>${dateLabel(t.date)}</td><td><b>${escapeHtml(t.symbol)}</b></td><td><span class="result-pill ${t.result}">${t.result==='win'?'승':'패'}</span></td><td>${t.rr}R</td><td class="${t.pnl>=0?'positive':'negative'}">${money(t.pnl)}</td><td>${escapeHtml(t.reason).slice(0,36)}</td></tr>`}

function drawChart(){
 const canvas=$('#performanceChart'); if(!canvas||!canvas.offsetWidth)return; const dpr=devicePixelRatio||1,w=canvas.offsetWidth,h=canvas.offsetHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);
 const trades=[...state.trades].sort((a,b)=>a.date.localeCompare(b.date)); if(!trades.length)return;
 const buckets=new Map();trades.forEach(t=>{const d=new Date(t.date+'T00:00:00');let key=t.date;if(chartPeriod==='week'){const monday=new Date(d);monday.setDate(d.getDate()-((d.getDay()+6)%7));key=monday.toISOString().slice(0,10)}else if(chartPeriod==='month')key=t.date.slice(0,7);else if(chartPeriod==='year')key=t.date.slice(0,4);buckets.set(key,(buckets.get(key)||0)+t.pnl/t.amount*100)});
 let cum=0;const pts=[...buckets.values()].map(value=>{cum+=value;return cum});const min=Math.min(0,...pts),max=Math.max(0,...pts),range=max-min||1,pad={x:42,y:22};
 c.font='10px DM Sans';c.fillStyle='#8a8a8a';c.strokeStyle='#e5e5e5';c.lineWidth=1;for(let i=0;i<5;i++){let y=pad.y+(h-pad.y*2)*i/4;c.beginPath();c.moveTo(pad.x,y);c.lineTo(w-10,y);c.stroke();let val=max-(range*i/4);c.fillText(`${val.toFixed(1)}%`,2,y+3)}
 const xy=pts.map((p,i)=>({x:pad.x+(w-pad.x-15)*(pts.length===1?.5:i/(pts.length-1)),y:pad.y+(max-p)/range*(h-pad.y*2)}));const grad=c.createLinearGradient(0,pad.y,0,h);grad.addColorStop(0,'rgba(25,25,25,.20)');grad.addColorStop(1,'rgba(25,25,25,0)');c.beginPath();c.moveTo(xy[0].x,h-pad.y);xy.forEach(p=>c.lineTo(p.x,p.y));c.lineTo(xy.at(-1).x,h-pad.y);c.fillStyle=grad;c.fill();c.beginPath();xy.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.strokeStyle='#222';c.lineWidth=2.5;c.stroke();xy.forEach(p=>{c.beginPath();c.arc(p.x,p.y,3,0,7);c.fillStyle='#fff';c.fill();c.strokeStyle='#222';c.lineWidth=2;c.stroke()});
}

const teamNames={scalping:'스캘핑팀',day:'단타팀',swing:'스윙팀',longterm:'장기투자팀'};
function renderTradeGrid(){const q=$('#tradeSearch').value.toLowerCase(),f=$('#tradeFilter').value;const list=[...state.trades].reverse().filter(t=>(activeTradeTeam==='all'||(t.team||'day')===activeTradeTeam)&&(f==='all'||t.result===f)&&(t.symbol.toLowerCase().includes(q)||t.reason.toLowerCase().includes(q)));$('#tradeGrid').innerHTML=list.map(t=>`<article class="panel trade-card ${t.result}" data-view-trade="${t.id}" tabindex="0"><div class="trade-chart">${safeImageUrl(t.chart)?`<img src="${attr(safeImageUrl(t.chart))}" alt="${escapeHtml(t.symbol)} 차트">`:'<div class="no-image">차트 이미지 없음</div>'}<span class="trade-team-label">${teamNames[t.team||'day']}</span></div><div class="trade-card-body"><div class="trade-card-top"><div><span class="trade-date">${t.date}</span><h3>${escapeHtml(t.symbol)}</h3><span class="direction-pill ${t.direction||'unset'}">${t.direction==='long'?'LONG · 롱':t.direction==='short'?'SHORT · 숏':'방향 미지정'}</span><span class="leverage-pill">${t.leverage?`${t.leverage}x`:'배율 미지정'}</span></div><span class="result-pill ${t.result}">${t.result==='win'?'승리':'패배'}</span></div><div class="trade-metrics"><span>손익비<b>${t.rr}R</b></span><span>투입 금액<b>₩${t.amount.toLocaleString()}</b></span><span>손익<b class="${t.pnl>=0?'positive':'negative'}">${money(t.pnl)}</b></span></div><p class="trade-reason">${escapeHtml(t.reason)}</p><div class="card-actions"><button class="text-btn" data-edit-trade="${t.id}">수정</button><button class="danger-btn" data-delete-trade="${t.id}">삭제</button></div></div></article>`).join('')||'<div class="panel empty-row">선택한 팀의 매매 기록이 없습니다.</div>'}

function renderNotes(){const q=$('#noteSearch').value.toLowerCase();const notes=[...state.notes].sort((a,b)=>b.updated-a.updated).filter(n=>(n.title+n.body).toLowerCase().includes(q));$('#noteList').innerHTML=notes.map(n=>`<div class="note-list-item ${n.id===activeNoteId?'active':''}" data-note="${n.id}"><strong>${escapeHtml(n.title||'제목 없음')}</strong><p>${escapeHtml(n.body||'내용 없음')}</p><small>${new Date(n.updated).toLocaleString('ko-KR')}</small></div>`).join('')||'<div class="empty-row">메모가 없습니다.</div>';renderEditor()}
function renderEditor(){const n=state.notes.find(n=>n.id===activeNoteId);if(!n){$('#noteEditor').innerHTML='<div class="note-placeholder"><span>▤</span><h2>매매 아이디어를 놓치지 마세요.</h2><p>왼쪽에서 메모를 선택하거나 새 메모를 만들어보세요.</p></div>';return}const images=n.images||[];$('#noteEditor').innerHTML=`<div class="editor-top"><input class="editor-title" id="noteTitle" value="${attr(n.title)}" placeholder="메모 제목"><div><span class="save-state">자동 저장</span> <button class="danger-btn" id="deleteNote">삭제</button></div></div><textarea class="editor-body" id="noteBody" placeholder="아이디어, 관찰, 원칙을 자유롭게 적어보세요.">${escapeHtml(n.body)}</textarea><div class="note-images">${images.map((src,index)=>({src,index})).filter(image=>safeImageUrl(image.src)).map(image=>`<figure><img src="${attr(safeImageUrl(image.src))}" alt="메모 첨부 이미지 ${image.index+1}"><button data-remove-note-image="${image.index}" aria-label="이미지 삭제">×</button></figure>`).join('')}</div><label class="note-image-upload"><input id="noteImageInput" type="file" accept="image/*" multiple hidden><span>＋ 사진 추가</span><small>PNG, JPG · 장당 최대 2MB</small></label>`}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function attr(v=''){return escapeHtml(v)}
function safeImageUrl(value){
  if(typeof value!=='string'||!value)return '';
  if(/^data:image\/(?:png|jpe?g|gif|webp);base64,[a-z0-9+/=\s]+$/i.test(value))return value;
  try{const url=new URL(value,location.href);return ['http:','https:','blob:'].includes(url.protocol)?url.href:''}catch{return ''}
}
function optimizeImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.82))};img.src=reader.result};reader.readAsDataURL(file)})}
async function addImagesToActiveNote(files){if(!files.length)return;if(files.some(file=>file.size>10*1024*1024)){toast('이미지는 장당 10MB 이하만 가능합니다.');return}const note=state.notes.find(n=>n.id===activeNoteId);if(!note)return;toast('사진을 최적화하는 중입니다.');try{const encoded=await Promise.all(files.map(optimizeImage));note.images=[...(note.images||[]),...encoded];note.updated=Date.now();try{save();renderNotes();toast(`${encoded.length}장의 사진을 추가했습니다.`)}catch(error){note.images.splice(-encoded.length);toast('브라우저 저장공간이 부족합니다. 기존 사진을 줄여주세요.')}}catch(error){toast('사진을 읽지 못했습니다. 다른 이미지를 사용해주세요.')}}

function openTradeForm(id=null){
  editingTradeId=id;const form=$('#tradeForm');form.reset();$('#formError').textContent='';$('#fileName').textContent='파일을 선택하거나 드래그하세요';
  const trade=state.trades.find(t=>t.id===id);$('#tradeModalEyebrow').textContent=trade?'EDIT TRADE':'NEW TRADE';$('#tradeModalTitle').textContent=trade?'매매 기록 수정':'매매 기록하기';$('#tradeSubmitBtn').textContent=trade?'수정 저장':'기록 저장';
  if(trade){form.date.value=trade.date;form.symbol.value=trade.symbol;form.team.value=trade.team||'day';form.direction.value=trade.direction||'long';form.leverage.value=trade.leverage||1;form.result.value=trade.result;form.rr.value=trade.rr;form.amount.value=trade.amount;form.pnl.value=trade.pnl;form.reason.value=trade.reason;$('#fileName').textContent=trade.chart?'기존 차트 이미지 유지':'파일을 선택하거나 드래그하세요'}else{form.date.value=new Date().toISOString().slice(0,10);form.team.value=activeTradeTeam==='all'?'day':activeTradeTeam;form.leverage.value=1}
  tradeModal.showModal();
}
function openTradeDetail(id){
  const t=state.trades.find(t=>t.id===id);if(!t)return;const modal=$('#tradeDetailModal'),reason=String(t.reason||'');modal.dataset.tradeId=id;$('#detailTitle').textContent=t.symbol;$('#tradeDetailContent').innerHTML=`${safeImageUrl(t.chart)?`<img class="detail-chart" src="${attr(safeImageUrl(t.chart))}" alt="${escapeHtml(t.symbol)} 차트">`:'<div class="detail-chart no-image">차트 이미지 없음</div>'}<div class="detail-badges"><span class="direction-pill ${t.direction||'unset'}">${t.direction==='long'?'LONG · 롱':t.direction==='short'?'SHORT · 숏':'방향 미지정'}</span><span class="leverage-pill">${t.leverage?`${t.leverage}x`:'배율 미지정'}</span><span class="result-pill ${t.result}">${t.result==='win'?'승리':'패배'}</span></div><div class="detail-grid"><div><span>날짜</span><b>${t.date}</b></div><div><span>레버리지</span><b>${t.leverage?`${t.leverage}배`:'미지정'}</b></div><div><span>손익비</span><b>${t.rr}R</b></div><div><span>투입 금액</span><b>₩${t.amount.toLocaleString()}</b></div><div><span>손익 금액</span><b class="${t.pnl>=0?'positive':'negative'}">${money(t.pnl)}</b></div></div><div class="detail-reason"><span>진입 근거 · ${reason.length}자</span><p>${escapeHtml(reason)}</p>${reason.length<60?'<small class="reason-warning">기존 기록이 60자 미만입니다. 수정 시 진입 조건·확인 지표·무효화 기준을 보완해 주세요.</small>':''}</div>`;modal.showModal();
}
function deleteTrade(id){if(!confirm('이 매매 기록을 삭제할까요?'))return false;state.trades=state.trades.filter(t=>t.id!==id);save();renderTradeGrid();renderDashboard();toast('매매 기록을 삭제했습니다.');return true}

$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)showView(go.dataset.go);const del=e.target.closest('[data-delete-trade]');if(del){e.stopPropagation();deleteTrade(+del.dataset.deleteTrade);return}const edit=e.target.closest('[data-edit-trade]');if(edit){e.stopPropagation();openTradeForm(+edit.dataset.editTrade);return}const card=e.target.closest('[data-view-trade]');if(card)openTradeDetail(+card.dataset.viewTrade);const note=e.target.closest('[data-note]');if(note){activeNoteId=+note.dataset.note;renderNotes()}const removeImage=e.target.closest('[data-remove-note-image]');if(removeImage){const active=state.notes.find(n=>n.id===activeNoteId);if(active){active.images=active.images||[];active.images.splice(+removeImage.dataset.removeNoteImage,1);active.updated=Date.now();save();renderNotes();toast('사진을 삭제했습니다.')}}if(e.target.id==='deleteNote'&&confirm('이 메모를 삭제할까요?')){state.notes=state.notes.filter(n=>n.id!==activeNoteId);activeNoteId=null;save();renderNotes();toast('메모를 삭제했습니다.')}});
$('#tradingReportTeams').onclick=e=>{const button=e.target.closest('[data-report-team]');if(!button)return;activeReportTeam=button.dataset.reportTeam;$$('[data-report-team]').forEach(item=>{const selected=item===button;item.classList.toggle('active',selected);item.setAttribute('aria-selected',String(selected))});loadTradingReports()};
$('#tradingReportState').onclick=e=>{if(e.target.closest('.report-retry'))loadTradingReports()};
const tradeModal=$('#tradeModal');$('#openTradeModal').onclick=()=>openTradeForm();$$('[data-close]').forEach(b=>b.onclick=()=>tradeModal.close());$('#tradeForm [name=chart]').onchange=e=>$('#fileName').textContent=e.target.files[0]?.name||'파일을 선택하거나 드래그하세요';
$('#tradeForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),file=e.target.chart.files[0];if(file?.size>2*1024*1024){$('#formError').textContent='이미지는 2MB 이하로 올려주세요.';return}const old=state.trades.find(t=>t.id===editingTradeId);let chart=old?.chart||null;if(file)chart=await new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)});let pnl=Number(f.get('pnl'));const result=f.get('result');if(result==='loss')pnl=-Math.abs(pnl);if(result==='win')pnl=Math.abs(pnl);const trade={id:editingTradeId||Date.now(),date:f.get('date'),symbol:f.get('symbol').trim(),team:f.get('team'),direction:f.get('direction'),leverage:Number(f.get('leverage')),result,rr:Number(f.get('rr')),amount:Number(f.get('amount')),pnl,reason:f.get('reason').trim(),chart};if(old)state.trades[state.trades.indexOf(old)]=trade;else state.trades.push(trade);save();e.target.reset();tradeModal.close();renderDashboard();if($('#tradesView').classList.contains('active'))renderTradeGrid();toast(old?'매매 기록을 수정했습니다.':'매매 기록을 저장했습니다.');editingTradeId=null};
$('#tradeSearch').oninput=renderTradeGrid;$('#tradeFilter').onchange=renderTradeGrid;window.onresize=()=>{if($('#dashboardView').classList.contains('active'))drawChart()};
$$('[data-period]').forEach(button=>button.onclick=()=>{chartPeriod=button.dataset.period;$$('[data-period]').forEach(item=>item.classList.toggle('active',item===button));drawChart()});
$$('[data-detail-close]').forEach(button=>button.onclick=()=>$('#tradeDetailModal').close());$('#detailEdit').onclick=()=>{const id=Number($('#tradeDetailModal').dataset.tradeId);$('#tradeDetailModal').close();openTradeForm(id)};$('#detailDelete').onclick=()=>{const id=Number($('#tradeDetailModal').dataset.tradeId);if(deleteTrade(id))$('#tradeDetailModal').close()};
$('#tradeGrid').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-view-trade]')){e.preventDefault();openTradeDetail(+e.target.dataset.viewTrade)}};
$('#newNote').onclick=()=>{const n={id:Date.now(),title:'새 메모',body:'',images:[],updated:Date.now()};state.notes.push(n);activeNoteId=n.id;save();renderNotes();setTimeout(()=>$('#noteTitle')?.select(),0)};$('#noteSearch').oninput=renderNotes;document.addEventListener('input',e=>{if(!['noteTitle','noteBody'].includes(e.target.id))return;const n=state.notes.find(n=>n.id===activeNoteId);n.title=$('#noteTitle').value;n.body=$('#noteBody').value;n.updated=Date.now();save();const s=$('.save-state');s.textContent='저장됨';clearTimeout(window.noteTimer);window.noteTimer=setTimeout(()=>renderNotes(),700)});
document.addEventListener('change',e=>{if(e.target.id==='noteImageInput')addImagesToActiveNote([...e.target.files])});
document.addEventListener('paste',e=>{if(!$('#notesView').classList.contains('active')||!activeNoteId)return;const images=[...e.clipboardData.items].filter(item=>item.type.startsWith('image/')).map(item=>item.getAsFile()).filter(Boolean);if(!images.length)return;e.preventDefault();addImagesToActiveNote(images)});

const researchItems=[];
const orgTeams=[
 {grade:'A',cls:'a',name:'경제 시황팀',count:8,desc:'시장 전체 방향과 경제 환경 분석',agents:['경제 데이터','금리·통화정책','환율·채권','경기 사이클','글로벌 경제','유동성·시장심리','Bull / Bear','팀 매니저']},
 {grade:'A',cls:'a',name:'미시 시황팀',count:8,desc:'업종·종목·수급 분석',agents:['업종 분석','종목 수급','거래량·거래대금','기관·외국인 매매','뉴스·공시 반응','시장 순환매','이상 움직임 감지','팀 매니저']},
 {grade:'B',cls:'b',name:'스캘핑팀',count:8,desc:'초단기 체결·호가 분석',agents:['호가창 분석','체결 흐름','초단기 기술적 분석','실시간 변동성 감지','슬리피지·거래비용','주문 실행','리스크 매니저','팀 매니저']},
 {grade:'B',cls:'b',name:'단타팀',count:8,desc:'당일~수일 단기 매매 분석',agents:['단기 기술적 분석','뉴스·공시 반응','수급·거래량 분석','장중 모멘텀','돌파 전략','당일 청산 관리','리스크 매니저','팀 매니저']},
 {grade:'B',cls:'b',name:'스윙팀',count:9,desc:'며칠~수개월 추세 분석',agents:['기본적 분석','일봉·주봉 추세','패턴·돌파','산업·거시 분석','실적 모멘텀','포지션 크기 계산','보유기간·청산 관리','리스크 매니저','팀 매니저']},
 {grade:'B',cls:'b',name:'장기투자팀',count:9,desc:'수개월~수년 기업가치 분석',agents:['재무제표 분석','기업가치 평가','현금흐름 분석','산업·경쟁우위','경영진·지배구조','장기 성장성','배당·자본배분','리스크 매니저','팀 매니저']},
 {grade:'X',cls:'x',name:'공통 연구·통제팀',count:6,desc:'전체 팀 지원, 연구 및 검증',agents:['AutoResearch','공통 데이터 품질관리','전략 백테스트','성과평가','모델·프롬프트 버전관리','감사 로그']}
];
let researchFilter='all';
function renderResearch(){const q=($('#researchSearch')?.value||'').toLowerCase();const list=researchItems.filter(x=>(researchFilter==='all'||x.type===researchFilter)&&(x.title+x.summary+x.author+x.tags.join(' ')).toLowerCase().includes(q));$('#researchCards').innerHTML=list.map(x=>`<article class="panel research-card"><div class="research-card-head"><span class="research-type ${x.type}">${x.label}</span><time>${x.date}</time></div><h3>${x.title}</h3><p>${x.summary}</p><div class="tag-row">${x.tags.map(t=>`<span>#${t}</span>`).join('')}</div><div class="research-metric"><strong>${x.metric}</strong><span>${x.status}</span></div><footer><span>${x.author}</span><button class="text-btn research-open" data-title="${attr(x.title)}">열기 →</button></footer></article>`).join('')||'<div class="panel empty-row">조건에 맞는 연구 자료가 없습니다.</div>'}
function renderOrganization(){$('#orgGrid').innerHTML=orgTeams.map(t=>`<article class="panel org-team ${t.cls}"><header><span class="grade ${t.cls}">${t.grade}</span><div><h3>${t.name}</h3><p>${t.desc}</p></div><b>${t.count}<small> AGENTS</small></b></header><div class="org-agents">${t.agents.map(a=>`<span><i></i>${a}</span>`).join('')}</div></article>`).join('')}
function openTemplateDetail(title,kind='문서'){let modal=$('#templateDetailModal');if(!modal){modal=document.createElement('dialog');modal.id='templateDetailModal';modal.innerHTML='<div class="template-detail"><button class="close-btn" aria-label="닫기">×</button><p class="eyebrow">TEMPLATE PREVIEW</p><h2></h2><div class="template-paper"><div><span>작성 팀</span><b>담당 에이전트 자동 표기 영역</b></div><div><span>핵심 판단</span><b>연동 후 분석 결과가 표시됩니다.</b></div><div><span>근거 및 데이터</span><p>데이터 출처, 분석 근거, 반대 시나리오와 신뢰도를 기록하는 본문 영역입니다. 현재는 사이트 구조 확인을 위한 템플릿입니다.</p></div><div><span>센터팀 결정</span><p>승인 · 보류 · 반려 및 리스크 코멘트가 이곳에 기록됩니다.</p></div></div></div>';document.body.appendChild(modal);modal.querySelector('.close-btn').onclick=()=>modal.close()}modal.querySelector('h2').textContent=`${title} · ${kind}`;modal.showModal()}
$$('[data-filter-group="report"] button').forEach(b=>b.onclick=()=>{$$('[data-filter-group="report"] button').forEach(x=>x.classList.toggle('active',x===b));$$('.report-item').forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.type!==b.dataset.filter)});
document.addEventListener('click',e=>{const collection=e.target.closest('[data-research-filter]');if(collection){researchFilter=collection.dataset.researchFilter;$$('[data-research-filter]').forEach(x=>x.classList.toggle('active',x===collection));renderResearch()}const report=e.target.closest('.report-open');if(report)openTemplateDetail(report.closest('.report-item').querySelector('h2,h3').textContent,'시황 리포트');const research=e.target.closest('.research-open');if(research)openTemplateDetail(research.dataset.title,'연구 기록')});
$('#researchSearch').oninput=renderResearch;$('#newResearch').onclick=()=>openTemplateDetail('새 연구 메모','작성 화면');
const CHAT_KEY='edge-fund-chat-v1';
const CHAT_CONVERSATION_KEY='edge-fund-conversations-v1';
const CHAT_API_BASE_KEY='edge-fund-api-base';
const CHAT_API_TOKEN_KEY='edge-fund-api-token';
const CHAT_CHANNELS={
  center:{role:'PM',team:'center'},
  macro:{role:'Bull',team:'macro'},
  micro:{role:'Bear',team:'micro'},
  scalping:{role:'Risk',team:'scalping'},
  day:{role:'Risk',team:'day'},
  swing:{role:'Risk',team:'swing'},
  longterm:{role:'Risk',team:'longterm'},
  research:{role:'Research',team:'research'}
};
const chatQuery=new URLSearchParams(location.search);
const CHAT_API_DEFAULT=location.hostname.endsWith('.vercel.app')?'/api/fund':'http://localhost:8765';
function chatApiToken(){const candidate=window.EDGE_FUND_API_TOKEN??localStorage.getItem(CHAT_API_TOKEN_KEY);if(typeof candidate!=='string')return '';const token=candidate.trim();return token&&!/[\u0000-\u001f\u007f]/.test(token)?token:''}
function chatApiAllowlist(){const configured=window.EDGE_FUND_API_ALLOWLIST;if(Array.isArray(configured))return configured;if(typeof configured==='string')return configured.split(',').map(value=>value.trim()).filter(Boolean);return []}
function normalizeChatApiBase(candidate){const value=String(candidate||CHAT_API_DEFAULT).trim();if(value==='/api/fund')return value;try{const url=new URL(value);if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.search||url.hash)return null;const isLocal=['localhost','127.0.0.1','::1'].includes(url.hostname);const allowed=chatApiAllowlist().some(entry=>{try{return new URL(entry).origin===url.origin}catch{return false}});return isLocal||allowed?url.origin:null}catch{return null}}
const CHAT_API_TOKEN=chatApiToken();
const configuredChatApiBase=location.hostname.endsWith('.vercel.app')?window.EDGE_FUND_API_BASE||CHAT_API_DEFAULT:window.EDGE_FUND_API_BASE||chatQuery.get('apiBase')||localStorage.getItem(CHAT_API_BASE_KEY)||CHAT_API_DEFAULT;
const requestedChatApiBase=configuredChatApiBase;
const CHAT_API_BASE=normalizeChatApiBase(requestedChatApiBase)||CHAT_API_DEFAULT;
if(String(requestedChatApiBase)!==CHAT_API_DEFAULT&&CHAT_API_BASE===CHAT_API_DEFAULT)console.warn('Blocked unsafe Fund API base URL. Add its origin to EDGE_FUND_API_ALLOWLIST to allow it.');
const chatSeed={center:[],macro:[],micro:[],scalping:[],day:[],swing:[],longterm:[],research:[]};
let chatState=JSON.parse(localStorage.getItem(CHAT_KEY)||'null')||chatSeed,activeChannel='center',chatBusy=false;
let chatConversations=JSON.parse(localStorage.getItem(CHAT_CONVERSATION_KEY)||'{}');
function chatTime(){return new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())}
function saveChat(){localStorage.setItem(CHAT_KEY,JSON.stringify(chatState))}
function proposalHtml(proposal){if(!proposal)return '';const title=proposal.title||proposal.name||'승인 제안';const detail=proposal.summary||proposal.description||proposal.rationale||'';const status=proposal.status||'PENDING';return `<div class="template-notice"><i>!</i><p><b>${escapeHtml(title)}</b><small>${escapeHtml(detail)}${detail?'<br>':''}상태: ${escapeHtml(status)}<br>PM 인증 연결 전 승인 불가</small><button type="button" disabled aria-disabled="true" title="승인 API 호출에는 actor_role=PM 인증 흐름이 필요합니다">PM 승인 (인증 필요)</button></p></div>`}
function renderChat(){const messages=chatState[activeChannel]||[];$('#chatMessages').innerHTML=`<div class="chat-date"><span>오늘 · ${new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric'}).format(new Date())}</span></div>${messages.map(m=>m.role==='user'?`<div class="message user-message"><div class="message-bubble"><p>${escapeHtml(m.text).replace(/\n/g,'<br>')}</p><time>${escapeHtml(m.time||'')}</time></div></div>`:`<div class="message agent-message${m.role==='proposal'?' proposal-message':''}"><span class="message-avatar">AI</span><div><b>${escapeHtml(m.agent||'Fund Team')}</b>${m.role==='proposal'?proposalHtml(m.proposal):`<div class="message-bubble"><p>${escapeHtml(m.text||'').replace(/\n/g,'<br>')}</p><time>${escapeHtml(m.time||'')}</time></div>`}</div></div>`).join('')}<div class="typing-indicator${chatBusy?' show':''}" id="typingIndicator"><span></span><span></span><span></span><small>Fund Team API 응답을 기다리는 중입니다</small></div>`;requestAnimationFrame(()=>{$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight})}
function selectChannel(button){activeChannel=button.dataset.channel;$$('.channel').forEach(x=>x.classList.toggle('active',x===button));$('#chatTeamName').textContent=button.dataset.name;$('#chatTeamDesc').textContent=button.dataset.desc;const avatar=button.querySelector('.channel-avatar');$('#chatAvatar').textContent=avatar.textContent;$('#chatAvatar').className=avatar.className;$('#chatInput').placeholder=`${button.dataset.name}에게 메시지를 보내세요...`;button.querySelector('.unread')?.remove();renderChat()}
async function chatFetch(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(`${CHAT_API_BASE}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),...(CHAT_API_TOKEN?{Authorization:`Bearer ${CHAT_API_TOKEN}`}:{})},signal:controller.signal});const raw=await response.text();let data={};if(raw){try{data=JSON.parse(raw)}catch{data={message:raw}}}if(!response.ok){const error=new Error(data.detail||data.error||data.message||`HTTP ${response.status}`);error.status=response.status;error.isContractError=response.status>=400&&response.status<500;throw error}return data}finally{clearTimeout(timer)}}
async function ensureConversation(channel,teamLabel){
  if(chatConversations[channel])return chatConversations[channel];
  const config=CHAT_CHANNELS[channel]||CHAT_CHANNELS.center;
  const data=await chatFetch('/chat/conversations',{method:'POST',body:JSON.stringify({role:config.role,team:config.team,metadata:{channel,team_label:teamLabel}})});
  const id=data.conversation_id||data.id||data.conversation?.conversation_id||data.conversation?.id;
  if(!id)throw new Error('conversation id가 응답에 없습니다');
  chatConversations[channel]=id;localStorage.setItem(CHAT_CONVERSATION_KEY,JSON.stringify(chatConversations));return id
}
function apiMessage(source,team,fallback={}){if(typeof source==='string')source={content:source};source=source||{};const text=source.content||source.text||source.message||source.response||'';const role=String(source.role||source.sender_role||'agent').toLowerCase();return {role:['user','human'].includes(role)?'user':'agent',agent:source.agent||source.agent_name||source.sender_name||source.role||fallback.agent||fallback.role||`${team} 매니저`,time:source.time||source.created_at||chatTime(),text:String(text)}}
function apiMessages(data,team){const fallbackSource=data.message||data.response||data.reply||data.data;const sources=Array.isArray(data.messages)?data.messages:(fallbackSource!=null?[fallbackSource]:[]);const messages=sources.filter(source=>source!=null).map(source=>apiMessage(source,team,data));const embeddedProposals=sources.filter(source=>source&&typeof source==='object'&&source.proposal).map(source=>source.proposal);const proposals=[...embeddedProposals,...(Array.isArray(data.proposals)?data.proposals:[]),...(data.proposal?[data.proposal]:[])];proposals.filter(proposal=>proposal!=null).forEach(proposal=>messages.push({role:'proposal',agent:data.agent||data.role||`${team} 매니저`,time:chatTime(),proposal}));if(!messages.length)throw new Error('메시지 본문이 응답에 없습니다');return messages}
function offlineDemoMessage(team,error){return {role:'agent',agent:'OFFLINE DEMO',time:chatTime(),text:`Fund Team API에 연결할 수 없어 오프라인 데모로 전환했습니다. (${error}) ${team}의 실제 분석 결과가 아니며, API 서버와 CORS 설정을 확인해 주세요.`}}
async function sendChat(text){if(chatBusy)return;const channel=activeChannel,team=$('.channel.active').dataset.name,config=CHAT_CHANNELS[channel]||CHAT_CHANNELS.center;chatState[channel]=chatState[channel]||[];chatState[channel].push({role:'user',time:chatTime(),text});saveChat();chatBusy=true;renderChat();$('#chatInput').disabled=true;try{const conversationId=await ensureConversation(channel,team);const requestId=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;const data=await chatFetch('/chat/send',{method:'POST',body:JSON.stringify({request_id:requestId,conversation_id:conversationId,content:text,text,message:text,role:config.role,team:config.team,metadata:{channel,team_label:team}})});chatState[channel].push(...apiMessages(data,team))}catch(error){const detail=error.name==='AbortError'?'요청 시간 초과':error.message;if(error.isContractError){chatState[channel].push({role:'agent',agent:`API ERROR ${error.status}`,time:chatTime(),text:`Fund Team API가 요청을 거부했습니다. (${detail}) 요청 계약과 서버 설정을 확인해 주세요.`});toast(`Fund Team API 요청 오류 · HTTP ${error.status}`)}else{chatState[channel].push(offlineDemoMessage(team,detail));toast('Fund Team API 연결 실패 · 오프라인 데모')}}finally{saveChat();chatBusy=false;$('#chatInput').disabled=false;renderChat();$('#chatInput').focus()}}
$$('.channel').forEach(button=>button.onclick=()=>selectChannel(button));$('#channelSearch').oninput=e=>{const q=e.target.value.toLowerCase();$$('.channel').forEach(x=>x.hidden=!(x.dataset.name+x.dataset.desc).toLowerCase().includes(q))};$$('[data-prompt]').forEach(button=>button.onclick=()=>{const input=$('#chatInput');input.value=button.dataset.prompt;input.focus()});$('#chatForm').onsubmit=e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;input.value='';input.style.height='auto';sendChat(text)};$('#chatInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatForm').requestSubmit()}};$('#chatInput').oninput=e=>{e.target.style.height='auto';e.target.style.height=`${Math.min(e.target.scrollHeight,120)}px`};
$$('[data-trade-tabs] button').forEach(button=>button.onclick=()=>{activeTradeTeam=button.dataset.team;$$('[data-trade-tabs] button').forEach(item=>item.classList.toggle('active',item===button));renderTradeGrid()});
$$('[data-position-tabs] button').forEach(button=>button.onclick=()=>{const team=button.dataset.team;$$('[data-position-tabs] button').forEach(item=>item.classList.toggle('active',item===button));let visible=0;$$('.position-card').forEach(card=>{const show=team==='all'||card.dataset.team===team;card.hidden=!show;if(show)visible++});$('[data-empty-position]').style.display=visible?'none':'grid'});
renderDashboard();
